apiVersion: v1
kind: Template
metadata:
  name: image-scan-pipelines
  annotations:
    description: "Jenkins Pipeline build configs for image scans"
    tags: "operator-pipeline,operators"
labels:
  app: image-scan-pipelines
parameters:
- description: "the api endpoint that invokes scanning of unscanned images"
  name: SCAN_UNSCANNED_IMGS_API_URL
  required: true
  value: "http://operator-pipeline-api:8080/scanUnscannedImages"
- description: "branch to check out the Jenkinsfiles in"
  name: BRANCH
  required: true
  value: "topic/jenkins-pipeline"
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: scan-image-pipeline
  spec:
    source:
      git:
        ref: ${BRANCH}
        uri: ssh://git@github.com/ldojo/demo-image-pipeline.git
      sourceSecret:
        name: aps-build-secret-ssh
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: scan-pipeline.Jenkinsfile
