apiVersion: v1
kind: Template
metadata: 
  name: image-scan-pipelines
  annotations:
    description: "Jenkins Pipeline build configs for image scans"
    tags: "operator-pipeline,operators"
labels:
  app: image-scan-pipelines
parameters:
- description: "the api endpoint that invokes scanning of unscanned images"
  name: SCAN_UNSCANNED_IMGS_API_URL
  required: true
  value: "http://operator-pipeline-api:8080/scanUnscannedImages"
- description: "branch to check out the Jenkinsfiles in"
  name: BRANCH
  required: true
  value: "master"
objects:
- apiVersion: v1
  kind: ConfigMap
  data:
    auths.json: |-
      {
        "auths": {
          "ear-operator-pipeline.apps.ilab-ctigtdc21d.ecs.dyn.nsroot.net": {
            "auth": "YWRtaW46cGFzc3dvcmQ="
          }
        }
      }
  metadata:
    name: image-scan-pipeline-auths
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: scan-unscanned-images 
  spec:
    source:
      git:
        ref: ${BRANCH} 
        uri: ssh://git@cedt-bitbucketcli.nam.nsroot.net:7999/cti_osc/image-scan-pipeline.git 
      sourceSecret:
        name: aps-build-secret-ssh
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: scan-unscanned-images.Jenkinsfile 
        env:
          - name: "SCAN_UNSCANNED_IMGS_API_URL"
            value: ${SCAN_UNSCANNED_IMGS_API_URL} 
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: scan-image-pipeline
  spec:
    source:
      git:
        ref: ${BRANCH}
        uri: ssh://git@cedt-bitbucketcli.nam.nsroot.net:7999/cti_osc/image-scan-pipeline.git
      sourceSecret:
        name: aps-build-secret-ssh
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: image-scan-pipeline.Jenkinsfile
        env:
          - name: "IMAGE_URL"
            value: "IMAGE_URL"
          - name: "EAR_AUTHS"
            valueFrom:
              configMapKeyRef:
                name: image-scan-pipeline-auths
                key: 'auths.json'
