# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.v1beta1 import project_pb2 as proto_dot_v1beta1_dot_project__pb2


class ProjectsStub(object):
    """[Projects](grafeas.io) API.

    Manages Grafeas `Projects`. Projects contain sets of other Grafeas entities
    such as `Notes` and `Occurrences`.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/grafeas.v1beta1.project.Projects/CreateProject',
                request_serializer=proto_dot_v1beta1_dot_project__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=proto_dot_v1beta1_dot_project__pb2.Project.FromString,
                )
        self.GetProject = channel.unary_unary(
                '/grafeas.v1beta1.project.Projects/GetProject',
                request_serializer=proto_dot_v1beta1_dot_project__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=proto_dot_v1beta1_dot_project__pb2.Project.FromString,
                )
        self.ListProjects = channel.unary_unary(
                '/grafeas.v1beta1.project.Projects/ListProjects',
                request_serializer=proto_dot_v1beta1_dot_project__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=proto_dot_v1beta1_dot_project__pb2.ListProjectsResponse.FromString,
                )
        self.DeleteProject = channel.unary_unary(
                '/grafeas.v1beta1.project.Projects/DeleteProject',
                request_serializer=proto_dot_v1beta1_dot_project__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ProjectsServicer(object):
    """[Projects](grafeas.io) API.

    Manages Grafeas `Projects`. Projects contain sets of other Grafeas entities
    such as `Notes` and `Occurrences`.
    """

    def CreateProject(self, request, context):
        """Creates a new project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Gets the specified project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Lists projects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Deletes the specified project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=proto_dot_v1beta1_dot_project__pb2.CreateProjectRequest.FromString,
                    response_serializer=proto_dot_v1beta1_dot_project__pb2.Project.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=proto_dot_v1beta1_dot_project__pb2.GetProjectRequest.FromString,
                    response_serializer=proto_dot_v1beta1_dot_project__pb2.Project.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=proto_dot_v1beta1_dot_project__pb2.ListProjectsRequest.FromString,
                    response_serializer=proto_dot_v1beta1_dot_project__pb2.ListProjectsResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=proto_dot_v1beta1_dot_project__pb2.DeleteProjectRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grafeas.v1beta1.project.Projects', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Projects(object):
    """[Projects](grafeas.io) API.

    Manages Grafeas `Projects`. Projects contain sets of other Grafeas entities
    such as `Notes` and `Occurrences`.
    """

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grafeas.v1beta1.project.Projects/CreateProject',
            proto_dot_v1beta1_dot_project__pb2.CreateProjectRequest.SerializeToString,
            proto_dot_v1beta1_dot_project__pb2.Project.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grafeas.v1beta1.project.Projects/GetProject',
            proto_dot_v1beta1_dot_project__pb2.GetProjectRequest.SerializeToString,
            proto_dot_v1beta1_dot_project__pb2.Project.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grafeas.v1beta1.project.Projects/ListProjects',
            proto_dot_v1beta1_dot_project__pb2.ListProjectsRequest.SerializeToString,
            proto_dot_v1beta1_dot_project__pb2.ListProjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grafeas.v1beta1.project.Projects/DeleteProject',
            proto_dot_v1beta1_dot_project__pb2.DeleteProjectRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
