# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1beta1/resource_details.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/v1beta1/resource_details.proto',
  package='grafeas.v1beta1.resource_details',
  syntax='proto3',
  serialized_options=b'\n#io.grafeas.v1beta1.resource_detailsP\001ZBgithub.com/grafeas/grafeas/proto/v1beta1/resource_details_go_proto\242\002\003GRA',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$proto/v1beta1/resource_details.proto\x12 grafeas.v1beta1.resource_details\"\x90\x01\n\x0eGenericDetails\x12N\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32=.grafeas.v1beta1.resource_details.GenericDetails.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Z\n\x0fOperatorDetails\x12G\n\toperators\x18\x01 \x03(\x0b\x32\x34.grafeas.v1beta1.resource_details.OperatorIdentifier\"3\n\x12OperatorIdentifier\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\tBq\n#io.grafeas.v1beta1.resource_detailsP\x01ZBgithub.com/grafeas/grafeas/proto/v1beta1/resource_details_go_proto\xa2\x02\x03GRAb\x06proto3'
)




_GENERICDETAILS_DETAILSENTRY = _descriptor.Descriptor(
  name='DetailsEntry',
  full_name='grafeas.v1beta1.resource_details.GenericDetails.DetailsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grafeas.v1beta1.resource_details.GenericDetails.DetailsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='grafeas.v1beta1.resource_details.GenericDetails.DetailsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=219,
)

_GENERICDETAILS = _descriptor.Descriptor(
  name='GenericDetails',
  full_name='grafeas.v1beta1.resource_details.GenericDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='details', full_name='grafeas.v1beta1.resource_details.GenericDetails.details', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GENERICDETAILS_DETAILSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=219,
)


_OPERATORDETAILS = _descriptor.Descriptor(
  name='OperatorDetails',
  full_name='grafeas.v1beta1.resource_details.OperatorDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operators', full_name='grafeas.v1beta1.resource_details.OperatorDetails.operators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=311,
)


_OPERATORIDENTIFIER = _descriptor.Descriptor(
  name='OperatorIdentifier',
  full_name='grafeas.v1beta1.resource_details.OperatorIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='grafeas.v1beta1.resource_details.OperatorIdentifier.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='grafeas.v1beta1.resource_details.OperatorIdentifier.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=364,
)

_GENERICDETAILS_DETAILSENTRY.containing_type = _GENERICDETAILS
_GENERICDETAILS.fields_by_name['details'].message_type = _GENERICDETAILS_DETAILSENTRY
_OPERATORDETAILS.fields_by_name['operators'].message_type = _OPERATORIDENTIFIER
DESCRIPTOR.message_types_by_name['GenericDetails'] = _GENERICDETAILS
DESCRIPTOR.message_types_by_name['OperatorDetails'] = _OPERATORDETAILS
DESCRIPTOR.message_types_by_name['OperatorIdentifier'] = _OPERATORIDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericDetails = _reflection.GeneratedProtocolMessageType('GenericDetails', (_message.Message,), {

  'DetailsEntry' : _reflection.GeneratedProtocolMessageType('DetailsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GENERICDETAILS_DETAILSENTRY,
    '__module__' : 'proto.v1beta1.resource_details_pb2'
    # @@protoc_insertion_point(class_scope:grafeas.v1beta1.resource_details.GenericDetails.DetailsEntry)
    })
  ,
  'DESCRIPTOR' : _GENERICDETAILS,
  '__module__' : 'proto.v1beta1.resource_details_pb2'
  # @@protoc_insertion_point(class_scope:grafeas.v1beta1.resource_details.GenericDetails)
  })
_sym_db.RegisterMessage(GenericDetails)
_sym_db.RegisterMessage(GenericDetails.DetailsEntry)

OperatorDetails = _reflection.GeneratedProtocolMessageType('OperatorDetails', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORDETAILS,
  '__module__' : 'proto.v1beta1.resource_details_pb2'
  # @@protoc_insertion_point(class_scope:grafeas.v1beta1.resource_details.OperatorDetails)
  })
_sym_db.RegisterMessage(OperatorDetails)

OperatorIdentifier = _reflection.GeneratedProtocolMessageType('OperatorIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORIDENTIFIER,
  '__module__' : 'proto.v1beta1.resource_details_pb2'
  # @@protoc_insertion_point(class_scope:grafeas.v1beta1.resource_details.OperatorIdentifier)
  })
_sym_db.RegisterMessage(OperatorIdentifier)


DESCRIPTOR._options = None
_GENERICDETAILS_DETAILSENTRY._options = None
# @@protoc_insertion_point(module_scope)
